server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/arthur.barbosa/Desenvolvimento/project-pratice/ws-microservice-alura/microservice-repo